#!/bin/sh
#| -*- mode: scheme; coding: utf-8; -*-
PATH="/usr/bin:/bin"
export PATH
cd /usr/local/lib/osrm-unstable/apiwrapper
exec gosh -I. -- $0 "$@"
|#

(use osrm-wrapper)

(define (config)
  '((osrm-service . ("localhost:5001" "/viaroute"))
    (waydb-file . "/home/karme/osm/unstable_ways.dbm")))
                  

(define (main args)
  (apply wrap-osrm-main (cons config args)))
