#!/bin/sh
#| -*- mode: scheme; coding: utf-8; -*-
PATH="/usr/bin:/bin"
export PATH
cd /usr/local/lib/osrm-unstable/apiwrapper
exec gosh -Ftokyocabinet -I. -- $0 "$@"
|#

(use osrm-wrapper)

(define (config)
  '((osrm-service . ("localhost:5001" "/viaroute"))))

(define (main args)
  (apply wrap-osrm-main (cons config args)))
