#!/bin/bash -xe
for i in format-json.scm \
    google-directions.scm \
    google-polyline.scm \
    partial-route.scm \
    routing.scm \
    runtime-compile.scm \
    debug.scm; do
cp -vuf ../../routing/svn/routingEngine/$i .
chmod -w $i
done
